### ISSUE TITLE
manager.access_token undefined but used in README example

### ISSUE THREAD

**Issue by n2ygk** [antechrestos/OAuth2Client#1]
manager.access_token is undefined from example in the README: 
```_logger.debug('Access got = %s', manager.access_token)
```
You actually set it to `manager._session.headers['Authorization']`.

**Comment by antechrestos** [comment]
Hi. Thanks for the feedback. I will take a look at it in the next few days. Cheers.

**Comment by n2ygk** [comment]
This is a really nice project. Very simply to use. I put it in a Jupyter
Notebook to teach people how to do OAuth with our REST APIs.
/a

**Comment by antechrestos** [comment]
Hi,
I defined a protected access to the access token . You can now access it by doing `managaer._access_token`. I also updated the README. 
Please let me know if this does not work.
I made a [new version of the library](https://pypi.python.org/pypi/oauth2-client)
