### ISSUE TITLE
Any plans to support Authorization Code Grant Flow with PKCE?

### ISSUE THREAD

**Issue by mathiasconradt** [antechrestos/OAuth2Client#4]
Are there any plans to support Authorization Code Grant Flow with [PKCE](https://tools.ietf.org/html/rfc7636)?

**Comment by antechrestos** [comment]
Would this [change](https://github.com/antechrestos/OAuth2Client/commit/2e5054f069e0fc8d82f0b3fa138e7decf0c18d71) be ok?

**Comment by antechrestos** [comment]
Any comment or feedback?

**Comment by dommcd** [comment]
Hey, bumping this thread to ask if you could update the[ package on pypi ](https://pypi.org/project/oauth2-client/) to have your latest update, Thanks for the great package btw :)

**Comment by antechrestos** [comment]
@dommcd doing some [cleaning](https://github.com/antechrestos/OAuth2Client/pull/10) and will make the publication after feedbacks got

**Comment by antechrestos** [comment]
@dommcd Sorry, forgot you... Yet did it...At last :smile:
